CREATE DATABASE task_manager
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE UTF8_GENERAL_CI;

USE task_manager;

CREATE TABLE tasks (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  edited TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  login VARCHAR(255)
) ENGINE=InnoDB CHARSET=utf8;
